site_name: BathyReq

theme:
  name: "material"
  features:
    - navigation.tabs
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocstrings

copyright: Copyright 2023 William Jenkins
repo_url: https://github.com/NeptuneProjects/BathyReq

nav:
  - Home: index.md
  - tutorials.md
  - "How-to Guides": how-to-guides.md
  - reference.md
  - explanation.md